apiVersion: v1
kind: PersistentVolume
metadata:
  name: springdb-mysql-data
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/springdb-mysql"