apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: api-unigps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: api.unigps.in
    http:
      paths:
      - path: /v2/*
        backend:
          serviceName: api-v2
          servicePort: 8080
      - path: /
        backend:
          serviceName: api-v1
          servicePort: 8080