apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: tutum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
# nodePort valid range 30000–32767