apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum
spec:
  selector:
    matchLabels:
      app: tutum
  replicas: 2
  template:
    metadata:
      labels:
        app: tutum
    spec:
      containers:
      - name: tutum
        image: tutum/hello-world
        ports:
        - containerPort: 80